# Generated by Django 3.2.18 on 2023-09-07 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Phone')),
                ('auth_code', models.CharField(blank=True, max_length=4)),
                ('invite_code', models.CharField(blank=True, max_length=6)),
                ('has_used_invite', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('gender', models.CharField(blank=True, choices=[('women', 'women'), ('men', 'men')], max_length=10, null=True, verbose_name='Gender')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='SuperUser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Join')),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last Login')),
                ('auth_code_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('email',),
            },
        ),
    ]
