# Generated by Django 3.2.18 on 2023-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
