# Generated by Django 3.2.18 on 2023-09-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_auth_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famyli', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Покойник',
                'verbose_name_plural': 'Покойники',
                'ordering': ('famyli',),
            },
        ),
    ]
